---

- name: Intro to Ansible Playbooks

  hosts: all



  tasks:

  - name: Add alfredo to sudo group

    user:

      name: alfredo 

      groups: sudo  # On Debian/Ubuntu; for CentOS/RHEL, use 'wheel'

      append: yes

  - name: Add the user 'bob'

    ansible.builtin.user:

      name: bob

    become: yes

    become_method: sudo

  - name: Upgrade all apt packages

    apt:

      force_apt_get: yes

      upgrade: dist

    become: yes