# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"


  config.vm.define "host1" do |host1|
    host1.vm.network :private_network, ip: "192.168.56.10"
    host1.vm.hostname = "host1"
  end


end

