# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"
  #config.vm.network :public_network, :public_network => "wlan0"
  #config.vm.network "public_network", bridge: 'Wi-Fi (AirPort)', adapter: 2
  #config.vm.network "public_network", bridge: 'wlan0', adapter: 1
  #config.vm.network "public_network", ip: '192.168.1.100'
  #config.vm.network :hostonly, "10.11.12.13"


  config.vm.hostname = "ansible-virtual-server"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end





end



















