# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"


  $script = <<-SCRIPT
  echo I am provisioning...
  sudo apt install ansible -y
  ansible --version
  (sudo useradd -m alfredo) && (sudo passwd alfredo) && (sudo usermod -aG sudo alfredo)
  apt-get install sshpass
  sshpass -V
  SCRIPT

  config.vm.define "host1" do |host1|
    host1.vm.network :private_network, ip: "192.168.56.9"
    host1.vm.hostname = "control-node"
  end


  config.vm.hostname = "ansible-virtual-server"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end











end



















